### ISSUE TITLE
Agharta ECIP-1056 / Morden testnet is scheduled. Is that right?

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/ECIPs#36]
https://github.com/etclabscore/ECIPs/blob/master/ECIPs/ecip-1056.md#abstract

Asking b/c there has been talk about replacing it with "Mordor." eg https://youtu.be/Msi6EItbslk?t=23664

**Comment by soc1c** [comment]
Potential Agharta timeline

- Morden Testnet (_deprecated_), Dec 11, 2019, 12pm UTC, block `5_348_435` (Gethc, Parity)
- Mordor Testnet, Jan 15, 2020, 12pm UTC, block `617_716` (Gethc, Parity, Mgeth)
- Kotti Testnet, Feb 05, 2020, 12pm UTC, block `2_028_202` (Parity, Mgeth)
- Classic Mainnet, Apr 15, 2020, 12pm UTC, _no block number required yet_

**Comment by meowsbits** [comment]
Thanks, closing via https://github.com/etclabscore/ECIPs/pull/35#discussion_r337568633
