### ISSUE TITLE
ECIP1062: eth_submitBlock proposal rationale

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/ECIPs#42]
> This removes the dependency for miners to have a geth node with accounts that need to be unlocked. Miners would be able to better isolate their private keys from the world, yeilding better security potential.
> https://github.com/etclabscore/ECIPs/blob/e31057c61d841fed159677436d19003e8663b06b/ECIPs/ecip-1062.md#rationale

@BelfordZ Miners do not need to unlock any account to mine. They only need to specify an etherbase address.

**Comment by meowsbits** [comment]
Deferring this issue to instead the place where discussion are supposed to be - #32.

**Comment by BelfordZ** [comment]
What I meant to say was that miners need to manually set their nodes etherbase to an address not managed by geth, OR they need to unlock the account / export the private key in order to gain access to the etc.
